# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths: 
      - 'account-management/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'account-management/**'

env:
  POM_PATH: /${{github.workspace}}/account-management/pom.xml

jobs:
  linter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINT_FILES: [account-management, account-management/*.*]

  build:

    runs-on: ubuntu-latest
    needs: [linter]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -DskipTests package --file "$POM_PATH"

  test:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3
    - name: Run Unit and Integration Tests
      run: mvn test --batch-mode -Dmaven.test.failure.ignore=true --file "$POM_PATH"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: test-reports
        path: account-management/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
